version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dist/index.html:/usr/share/nginx/html/index.html
      - ./dist/assets:/usr/share/nginx/html/assets
      - ./templates:/etc/nginx/templates
    env_file:
      - ./.env
    command: ["nginx", "-g", "daemon off;"]