FROM node:latest as front-project
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm i
COPY . .
RUN npm run build

FROM nginx:latest
COPY --from=front-project /app/dist/index.html /usr/share/nginx/html
COPY --from=front-project /app/dist/assets /usr/share/nginx/html/assets
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]